### ISSUE TITLE
Fix alignment circle goals with subgoals

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1411]
**Is your feature request related to a problem? Please describe.**
It's very annoying when things are not aligned.

**Describe the solution you'd like**
Align outer circle with the inner circle.

**Describe alternatives you've considered**
A different way of showing subgoals, like with a number or circles inside the circle. This is not as clear and removes the possibility for an icon/image inside the circle.

**Additional context**
![20230819_16581.jpg](https://github.com/tijlleenders/ZinZen/assets/44887755/e11b3cee-fb72-48e6-b872-0d2abd5b3ed6)

**Comment by Tushar-4781** [comment]
Resolved by #1417

**Comment by tijlleenders** [comment]
@Tushar-4781 This is not resolved. We just decided it was taking too much time to fix.

Keeping this open in case anyone out there wants to give it a try.

**Comment by tijlleenders** [comment]
@Tushar-4781 You did something in one of last PRs that fixes this issue.

Sooooo much better now!

**Comment by tijlleenders** [comment]
![Screenshot_20230903_e.jpg](https://github.com/tijlleenders/ZinZen/assets/44887755/c6f7bbe3-30b5-4a7c-93b6-61fa57e3b586)
